# Generated by Django 5.1.4 on 2025-06-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0002_chaivariety_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chaivariety',
            name='image',
        ),
        migrations.AddField(
            model_name='chaivariety',
            name='image_path',
            field=models.CharField(default='media/chai/default.png', max_length=200),
        ),
    ]
